### ISSUE TITLE
Is there a way to wait for the keyboard to be connected?

### ISSUE THREAD

**Issue by revsuine** [xz-dev/numlockw#1]
Or at least, I assume that's my problem.

I am running a script with contents

```sh
#!/bin/bash

sudo numlockw on
```

which is run by a `riverctl spawn` command in my `~/.config/river/init`. However this doesn't turn my numlock on.

When I run the script manually it works, including with `riverctl spawn`. So I assume what's happening is that river runs this command before my keyboard is connected, and so it doesn't have any effect.

Edit: Hit ctrl enter instead of enter and posted too soon. Finished the post.

**Comment by xz-dev** [comment]
To clarify, your keyboard is always connected to the computer.
But when you use the sudo numlockw on command in ~/.config/river/init, it has no effect, right?

**Comment by revsuine** [comment]
> To clarify, your keyboard (and you only have one keyboard) is always connected to the computer. But when you use the `sudo numlockw on` command in `~/.config/river/init`, it has no effect, right?

Yes, it is always plugged in/physically connected. It only has no effect in `~/.config/river/init` with `riverctl spawn "/path/to/script"` (script contents above), however when I run `riverctl spawn "path/to/script"` manually (i.e. after everything has loaded in/after the init script has run), or when I just run `/path/to/script` manually, it does work.

I have numlockw set up to work with no password from sudo so it's not that. When I enter the command it works correctly without any further input after hitting enter on the command.

**Comment by xz-dev** [comment]
> Caps lock LED does not light up for me

Seems due script not work at all, I think you can try:

```bash
#!/bin/bash

OUTPUT_FILE="/path/to/your/output_file.log"

sudo numlockx on &> "$OUTPUT_FILE"
```

And see the log file to know what happened.

**Comment by revsuine** [comment]
Thanks, I've got this output:

```
Sun 18 Aug 00:43:30 BST 2024
Traceback (most recent call last):
  File "/usr/local/bin/numlockw", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 119, in main
    args.func()
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 66, in on
    toggle(True)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 56, in toggle
    status = numlock_get_status(devices)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 49, in numlock_get_status
    if LED_NUML in device.leds():
                   ^^^^^^^^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/device.py", line 258, in leds
    leds = _input.ioctl_EVIOCG_bits(self.fd, ecodes.EV_LED)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function ioctl_EVIOCG_bits> returned NULL without setting an exception
Sun 18 Aug 12:47:48 BST 2024
Traceback (most recent call last):
  File "/usr/local/bin/numlockw", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 119, in main
    args.func()
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 66, in on
    toggle(True)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 56, in toggle
    status = numlock_get_status(devices)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 49, in numlock_get_status
    if LED_NUML in device.leds():
                   ^^^^^^^^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/device.py", line 258, in leds
    leds = _input.ioctl_EVIOCG_bits(self.fd, ecodes.EV_LED)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function ioctl_EVIOCG_bits> returned NULL without setting an exception
```

**Comment by xz-dev** [comment]
I have a quick fix for that, what a min and `pipx install git+https://github.com/xz-dev/numlockw.git --force` to try it again.

**Comment by xz-dev** [comment]
And if possible, add `numlockw list-devices` to your script.
Then we will know which device have the NumLock

**Comment by revsuine** [comment]
Hi, thank you for fixing this and making numlockw in the first place too! Everything works fine for me now after an update :)

**Comment by revsuine** [comment]
Oh if you wanted to know what the device in question is, it's a Corsair K70 M.2. However interestingly when I run `numlockw list-devices` it says:

```
Path | Device Name | Physical Topology
/dev/input/event3 | Logitech G203 LIGHTSYNC Gaming Mouse Keyboard | usb-0000:0a:00.3-1/input1
```

The Logitech G203 Lightsync is my mouse, not my keyboard. I do not have a Logitech keyboard, and my mouse does not have a num lock. So that's interesting. But it still works as in it enables my num lock when I start River so I'm not bothered

**Comment by revsuine** [comment]
Ok, update. I've noticed now that my numlock is randomly turning off. It does turn on upon starting river as per my river init script, but then it only stays on for several minutes before turning off again. Not sure how to debug this. I'll reopen but if this is best to be a separate issue I can also create a new issue.

**Comment by xz-dev** [comment]
> Oh if you wanted to know what the device in question is, it's a Corsair K70 M.2. However interestingly when I run `numlockw list-devices` it says:
> 
> ```
> Path | Device Name | Physical Topology
> /dev/input/event3 | Logitech G203 LIGHTSYNC Gaming Mouse Keyboard | usb-0000:0a:00.3-1/input1
> ```
> 
> The Logitech G203 Lightsync is my mouse, not my keyboard. I do not have a Logitech keyboard, and my mouse does not have a num lock. So that's interesting. But it still works as in it enables my num lock when I start River so I'm not bothered
> 
> The log still shows an error too. My script now says:
> 
> ```shell
> #!/bin/bash
> 
> LOGFILE="$HOME/.log/numlockw"
> 
> numlockw list-devices &>> $LOGFILE
> sudo numlockw on &>> $LOGFILE
> ```
> 
> The log says:
> 
> ```
> Path | Device Name | Physical Topology
> /dev/input/event3 | Logitech G203 LIGHTSYNC Gaming Mouse Keyboard | usb-0000:0a:00.3-1/input1
> Traceback (most recent call last):
>   File "/usr/local/bin/numlockw", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 122, in main
>     args.func()
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 69, in on
>     toggle(True)
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 65, in toggle
>     numlock_led_switch(device, not status)
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 43, in numlock_led_switch
>     device.set_led(LED_NUML, 1 if status else 0)
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/device.py", line 272, in set_led
>     self.write(ecodes.EV_LED, led_num, value)
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/eventio.py", line 85, in wrapper
>     return func(*args)
>            ^^^^^^^^^^^
>   File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/eventio.py", line 137, in write
>     _uinput.write(self.fd, etype, code, value)
> OSError: [Errno 19] No such device
> ```
> 
> However despite this error, my num lock is still turning on upon starting River, so I think it's fine?

Thanks for your addition, I will try to fix it

**Comment by xz-dev** [comment]
> Ok, update. I've noticed now that my numlock is randomly turning off. It does turn on upon starting river as per my river init script, but then it only stays on for several minutes before turning off again. Not sure how to debug this. I'll reopen but if this is best to be a separate issue I can also create a new issue. Likely related to the error above

Might useful: https://codeberg.org/river/river/issues/1120

**Comment by revsuine** [comment]
> Ok, update. I've noticed now that my numlock is randomly turning off. It does turn on upon starting river as per my river init script, but then it only stays on for several minutes before turning off again. Not sure how to debug this. I'll reopen but if this is best to be a separate issue I can also create a new issue. Likely related to the error above

Just a bit of additional information: I've realised that it's not actually turning on and then off again later, it's just only turning the LED on but when I try to type numbers with the num pad it doesn't work. When I press the num lock key manually it works. I've also tried a `sleep 10` but that didn't change the behaviour (except for delay it obviously). I assume the LED just turns off when the keyboard realises num lock isn't actually on.

Thanks for your work on this, appreciate it.

**Comment by xz-dev** [comment]
> > Ok, update. I've noticed now that my numlock is randomly turning off. It does turn on upon starting river as per my river init script, but then it only stays on for several minutes before turning off again. Not sure how to debug this. I'll reopen but if this is best to be a separate issue I can also create a new issue. Likely related to the error above
> 
> Just a bit of additional information: I've realised that it's not actually turning on and then off again later, it's just only turning the LED on but when I try to type numbers with the num pad it doesn't work. When I press the num lock key manually it works. I've also tried a `sleep 10` but that didn't change the behaviour (except for delay it obviously). I assume the LED just turns off when the keyboard realises num lock isn't actually on.
> 
> Thanks for your work on this, appreciate it.

I got it.

You can use [this way](https://codeberg.org/river/river/issues/1120#issuecomment-2110749) to fix it.

**Comment by revsuine** [comment]
I changed my script to

```bash
#!/bin/bash

LOGFILE="$HOME/.log/numlockw"

# redirect stdout and stderr to the logfile
exec >> $LOGFILE
exec 2>&1

date
numlockw list-devices
# https://codeberg.org/river/river/issues/1120#issuecomment-2110749
riverctl keyboard-group-create keyboard_group
riverctl keyboard-group-add keyboard_group keyboard-6940-6985-ckb1 # corsair kb
riverctl keyboard-group-add keyboard_group keyboard-1-1-py-evdev-uinput
sudo numlockw on
```

And having the same effect, with the same error:

```
Path | Device Name | Physical Topology
/dev/input/event3 | Logitech G203 LIGHTSYNC Gaming Mouse Keyboard | usb-0000:0a:00.3-1/input1
Traceback (most recent call last):
  File "/usr/local/bin/numlockw", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 122, in main
    args.func()
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 69, in on
    toggle(True)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 65, in toggle
    numlock_led_switch(device, not status)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/numlockw/__main__.py", line 43, in numlock_led_switch
    device.set_led(LED_NUML, 1 if status else 0)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/device.py", line 272, in set_led
    self.write(ecodes.EV_LED, led_num, value)
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/eventio.py", line 85, in wrapper
    return func(*args)
           ^^^^^^^^^^^
  File "/opt/pipx/venvs/numlockw/lib/python3.12/site-packages/evdev/eventio.py", line 137, in write
    _uinput.write(self.fd, etype, code, value)
OSError: [Errno 19] No such device
```

`riverctl list-inputs` shows:

```
keyboard-0-1-Power_Button
	configured: false

keyboard-0-1-Power_Button
	configured: false

pointer-1133-49298-Logitech_G203_LIGHTSYNC_Gaming_Mouse
	configured: false

keyboard-6940-6985-ckb1:_CORSAIR_K70_RGB_MK.2_Mechanical_Gaming_Keyboard_vKB
	configured: false

pointer-6940-6985-ckb1:_CORSAIR_K70_RGB_MK.2_Mechanical_Gaming_Keyboard_vM
	configured: false

keyboard-1133-49298-Logitech_G203_LIGHTSYNC_Gaming_Mouse_Keyboard
	configured: false

pointer-1133-49298-Logitech_G203_LIGHTSYNC_Gaming_Mouse_Keyboard
	configured: false
```

My keyboard is Corsair, not Logitech, so the issue might be related to how numlockw seems to think my mouse is my keyboard/doesn't seem to see the Corsair keyboard?

I've also finally realised that numlockw isn't actually working for me outside of river init either; it's doing the same thing, turning the LED on but not actually enabling num lock. I had assumed it was actually turning on but I hadn't tried typing numbers with the num pad, and typing numbers with the num pad doesn't work unless I physically press num lock.

Sorry about the headache, it might just be something about my specific hardware.

Interestingly though I'm using [the numlock hook in my mkinitcpio](https://wiki.archlinux.org/title/Activating_numlock_on_bootup#Early_bootup_(mkinitcpio)) (from the Arch Wiki article you linked in the README) which is working, like actually working I've tried typing numbers into my username when logging in via tty. Launching river turns num lock off for me so I either need a way to re-enable it (which I've been trying to do with numlockw) or River needs to not reset numlock state, which I'm not sure is possible.

**Comment by xz-dev** [comment]
Now it's fixed:

```bash
> pipx install git+https://github.com/xz-dev/numlockw.git --force
> sudo numlockw list-devices
Path | Device Name | Physical Topology | LED Status
/dev/input/event5 | Dell KB216 Wired Keyboard | usb-0000:65:00.0-2/input0 | OFF
/dev/input/event3 | AT Translated Set 2 keyboard | isa0060/serio0/input0 | OFF
/dev/input/event13 | Keychron Keychron V4 | usb-0000:65:00.3-1.2.2.2/input0 | ON
/dev/input/event17 | Keychron Keychron V4 Keyboard | usb-0000:65:00.3-1.2.2.2/input2 | ON
/dev/input/event19 | Logitech G502 HERO Gaming Mouse Keyboard | usb-0000:65:00.3-1.2.2.3/input1 | OFF
/dev/input/event27 | numlockw-evdev-uinput | py-evdev-uinput | OFF
> numlockw --device-name "Dell KB216 Wired Keyboard" on
```

Then, click your keyboard. You will see the NumLock LED been light
And if you not both use two keyboard, the NumLock will working fine (it's a bug of riverwm)
